import Head from "next/head";
import Form from "../components/Form";
import TodoList from "../components/TodoList";
import Handler from "../components/Handler";

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Form />
      <TodoList />
      <br />
      <Handler />
    </>
  );
}
